language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r src/requirements.txt
# command to run tests
script:
  - nosetests
  - pylint --rcfile .pylintrc src/*.py
