language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r src/requirements.txt

# pre-flight checks!
jobs:
  include:
    - stage: linting
      script: pylint --rcfile .pylintrc src/*.py
    - stage: unittests
      script: nosetests
